#
# Jekyll configuration
#
auto: true
server: false
permalink: /:title
markdown: rdiscount

#
# Site configuration
#
title: "tech-watch"
description: "Presentation about technology watch for everyone"
baseUrl: "tech-watch"
author: "Bastien Lemale"
email: "blemale@excilys.com"
