#
# Jekyll configuration
#
auto: true
server: false
permalink: /:title
markdown: rdiscount

#
# Site configuration
#
title: "tech-watch-4-excilys-interns"
description: "Presentation about technology watch for Excilys interns"
author: "Bastien Lemale"
email: "blemale@excilys.com"
